//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientEncTSSign.EncTSSignReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EncTSSignReference.IAdminConfigEncTSSign")]
    public interface IAdminConfigEncTSSign {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminConfigEncTSSign/getServerTime", ReplyAction="http://tempuri.org/IAdminConfigEncTSSign/getServerTimeResponse")]
        string getServerTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminConfigEncTSSign/getServerTime", ReplyAction="http://tempuri.org/IAdminConfigEncTSSign/getServerTimeResponse")]
        System.Threading.Tasks.Task<string> getServerTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminConfigEncTSSign/getAdminToken", ReplyAction="http://tempuri.org/IAdminConfigEncTSSign/getAdminTokenResponse")]
        string getAdminToken();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminConfigEncTSSign/getAdminToken", ReplyAction="http://tempuri.org/IAdminConfigEncTSSign/getAdminTokenResponse")]
        System.Threading.Tasks.Task<string> getAdminTokenAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminConfigEncTSSignChannel : ClientEncTSSign.EncTSSignReference.IAdminConfigEncTSSign, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminConfigEncTSSignClient : System.ServiceModel.ClientBase<ClientEncTSSign.EncTSSignReference.IAdminConfigEncTSSign>, ClientEncTSSign.EncTSSignReference.IAdminConfigEncTSSign {
        
        public AdminConfigEncTSSignClient() {
        }
        
        public AdminConfigEncTSSignClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminConfigEncTSSignClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminConfigEncTSSignClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminConfigEncTSSignClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getServerTime() {
            return base.Channel.getServerTime();
        }
        
        public System.Threading.Tasks.Task<string> getServerTimeAsync() {
            return base.Channel.getServerTimeAsync();
        }
        
        public string getAdminToken() {
            return base.Channel.getAdminToken();
        }
        
        public System.Threading.Tasks.Task<string> getAdminTokenAsync() {
            return base.Channel.getAdminTokenAsync();
        }
    }
}
