//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTSSign.TSSignReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TSSignReference.IAdminConfigTSSign")]
    public interface IAdminConfigTSSign {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/IAdminConfigTSSign/getServerTime", ReplyAction="http://tempuri.org/IAdminConfigTSSign/getServerTimeResponse")]
        string getServerTime();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/IAdminConfigTSSign/getServerTime", ReplyAction="http://tempuri.org/IAdminConfigTSSign/getServerTimeResponse")]
        System.Threading.Tasks.Task<string> getServerTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/IAdminConfigTSSign/getAdminToken", ReplyAction="http://tempuri.org/IAdminConfigTSSign/getAdminTokenResponse")]
        string getAdminToken();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/IAdminConfigTSSign/getAdminToken", ReplyAction="http://tempuri.org/IAdminConfigTSSign/getAdminTokenResponse")]
        System.Threading.Tasks.Task<string> getAdminTokenAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminConfigTSSignChannel : ClientTSSign.TSSignReference.IAdminConfigTSSign, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminConfigTSSignClient : System.ServiceModel.ClientBase<ClientTSSign.TSSignReference.IAdminConfigTSSign>, ClientTSSign.TSSignReference.IAdminConfigTSSign {
        
        public AdminConfigTSSignClient() {
        }
        
        public AdminConfigTSSignClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminConfigTSSignClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminConfigTSSignClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminConfigTSSignClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getServerTime() {
            return base.Channel.getServerTime();
        }
        
        public System.Threading.Tasks.Task<string> getServerTimeAsync() {
            return base.Channel.getServerTimeAsync();
        }
        
        public string getAdminToken() {
            return base.Channel.getAdminToken();
        }
        
        public System.Threading.Tasks.Task<string> getAdminTokenAsync() {
            return base.Channel.getAdminTokenAsync();
        }
    }
}
