//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientNoSecurity.NoSecurityReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoSecurityReference.IAdminConfig")]
    public interface IAdminConfig {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminConfig/getServerTime", ReplyAction="http://tempuri.org/IAdminConfig/getServerTimeResponse")]
        string getServerTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminConfig/getServerTime", ReplyAction="http://tempuri.org/IAdminConfig/getServerTimeResponse")]
        System.Threading.Tasks.Task<string> getServerTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminConfig/getAdminToken", ReplyAction="http://tempuri.org/IAdminConfig/getAdminTokenResponse")]
        string getAdminToken();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminConfig/getAdminToken", ReplyAction="http://tempuri.org/IAdminConfig/getAdminTokenResponse")]
        System.Threading.Tasks.Task<string> getAdminTokenAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminConfigChannel : ClientNoSecurity.NoSecurityReference.IAdminConfig, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminConfigClient : System.ServiceModel.ClientBase<ClientNoSecurity.NoSecurityReference.IAdminConfig>, ClientNoSecurity.NoSecurityReference.IAdminConfig {
        
        public AdminConfigClient() {
        }
        
        public AdminConfigClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminConfigClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminConfigClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminConfigClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getServerTime() {
            return base.Channel.getServerTime();
        }
        
        public System.Threading.Tasks.Task<string> getServerTimeAsync() {
            return base.Channel.getServerTimeAsync();
        }
        
        public string getAdminToken() {
            return base.Channel.getAdminToken();
        }
        
        public System.Threading.Tasks.Task<string> getAdminTokenAsync() {
            return base.Channel.getAdminTokenAsync();
        }
    }
}
